name: NixOS Cache-nix-action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
            extra-substituters = https://nix-community.cachix.org
            extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: ${{ runner.os }}-nixos-inspiron-${{ hashFiles('flake.lock') }}
          restore-prefixes-first-match: |
            ${{ runner.os }}-nixos-inspiron-
          gc-max-store-size-linux: 8G   # 必要に応じて調整（7G〜10Gくらいが現実的）
          save: true

      # flake check + build
      - name: Flake check
        run: nix flake check --accept-flake-config

      - name: Build system
        run: |
          nix build .#nixosConfigurations.Inspiron14-5445.config.system.build.toplevel \
            --accept-flake-config \
            --print-build-logs
